### ISSUE TITLE
Problems in notebooks dataset files

### ISSUE THREAD

**Issue by Tushn** [svakulenk0/KBQA#2]
Hello,

I'm trying to execute: "notebooks/1_question_parser.ipynb", but '1hop' and '2hop' are not exist in JSON files. I'd like to understand how to get or generate them.

Other question, how is possible to reproduce this article experiment:
http://www.vldb.org/pvldb/vol10/p565-cui.pdf

I could not understand project in overview, thanks a lot, for any help.

**Comment by svakulenk0** [comment]
Hi Sorry just noticed your question. I have added a notebook with pre-processing scripts as well notebooks/0_preprocessing.ipynb Let me know if it works for you!
